"""Add mission status and timestamps

Revision ID: 17f8fb569a7e
Revises: 07e2ff7574c7
Create Date: 2025-06-25 13:05:01.952102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17f8fb569a7e'
down_revision: Union[str, Sequence[str], None] = '07e2ff7574c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waypoints_id'), table_name='waypoints')
    op.drop_table('waypoints')
    op.alter_column('missions', 'status',
               existing_type=postgresql.ENUM('pending', 'in_progress', 'completed', 'aborted', name='missionstatus'),
               nullable=False,
               existing_server_default=sa.text("'pending'::missionstatus"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('missions', 'status',
               existing_type=postgresql.ENUM('pending', 'in_progress', 'completed', 'aborted', name='missionstatus'),
               nullable=True,
               existing_server_default=sa.text("'pending'::missionstatus"))
    op.create_table('waypoints',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sequence', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mission_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], name=op.f('waypoints_mission_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('waypoints_pkey'))
    )
    op.create_index(op.f('ix_waypoints_id'), 'waypoints', ['id'], unique=False)
    # ### end Alembic commands ###
