"""Add location fields to Drone

Revision ID: 25258d79323e
Revises: d54ffa6948c3
Create Date: 2025-06-26 12:06:50.372168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25258d79323e'
down_revision: Union[str, Sequence[str], None] = 'd54ffa6948c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waypoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waypoints_id'), 'waypoints', ['id'], unique=False)
    op.add_column('drones', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('drones', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drones', 'longitude')
    op.drop_column('drones', 'latitude')
    op.drop_index(op.f('ix_waypoints_id'), table_name='waypoints')
    op.drop_table('waypoints')
    # ### end Alembic commands ###
