"""Add drone status and current_mission_id

Revision ID: d54ffa6948c3
Revises: 17f8fb569a7e
Create Date: 2025-06-25 13:12:05.412130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd54ffa6948c3'
down_revision: Union[str, Sequence[str], None] = '17f8fb569a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("drones", "id", type_=sa.Integer(), postgresql_using="id::integer")
    op.drop_index(op.f('idx_drones_location'), table_name='drones', postgresql_using='gist')
    op.create_index(op.f('ix_drones_id'), 'drones', ['id'], unique=False)
    op.drop_column('drones', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drones', sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_drones_id'), table_name='drones')
    op.create_index(op.f('idx_drones_location'), 'drones', ['location'], unique=False, postgresql_using='gist')
    op.alter_column('drones', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
